### ISSUE TITLE
Demo site down

### ISSUE THREAD

**Issue by urras** [kevinburke/doony#83]
Hello, 
The demo site on http://doony.org (166.78.9.27:8080) appears to time out for me and at least 3 other people. Perhaps someone could offer some insight as to why that is?

**Comment by ssbarnea** [comment]
With the site down...is useless, it could at least have few screenshots :)

There are already many skins for jenkins, I guess I will have to skip evaluating this one.

**Comment by kevinburke** [comment]
Should be back up at jenkins.doony.org. I admit it doesn't look that great
anymore due to CSS changes.

Sadly I don't do that much work on Jenkins anymore, as I've switched roles.
If anyone is willing to take up work on the project, I'll hand over the
keys to the kingdom.


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by urras** [comment]
:+1: Thanks for putting it back up

**Comment by ssbarnea** [comment]
Thanks!

/sorin
