### ISSUE TITLE
Doony (the pet) is being put to sleep

### ISSUE THREAD

**Issue by kevinburke** [kevinburke/doony#95]
I named this project after my girlfriend's dog Doony. Doony is getting very old and is sadly being put to sleep today. He was a great companion to Laura's family for many years. He was always in good spirits. 

He always knew when someone was making or eating food. One of his best days was when he got an In N Out burger I bought and forgot to eat. He wasn't the best at turning around. 

He is 17 years old.

<img src="https://lh3.googleusercontent.com/-WRZ1m_hlBkw/WEH9j3a7i2I/AAAAAAAAABc/sHuf_LsMveYut1USM3h_kLcOe-B2S5ebACL0B/h2048/2016-12-02.jpg" />

**Comment by ssbarnea** [comment]
Sorry to hear about your beloved pet. One question that comes into my mind is regarding the future of Doony the project?! Is it also put to "sleep"? 

Somehow I see that the build buttons are broken which makes me thing that this may be the case too. Sadly because Doony was the most popular Jenking theme based on number of stars.  Now I am looking for something else.

http://s3.sbarnea.com/ss/Jenkins_2017-03-23_18-32-20.png
